apiVersion: v1
kind: Service
metadata:
  name: micro
spec:
  type: NodePort
  selector:
    app: micro
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-canary
spec:
  type: NodePort
  selector:
    app: micro
    version: canary
  ports:
    - port: 80
      nodePort: 30001
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: micro
          imagePullPolicy: Never
          image: micro:v1
          command:
            - "npm"
            - "start"
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-canary
spec:
  replicas: 0
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
        version: canary
    spec:
      containers:
        - name: micro
          imagePullPolicy: Never
          image: micro:v2
          command:
            - "npm"
            - "start"
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
